// Script to generate high-fidelity, verified 1000+ questionnaire knowledge matrix
import fs from 'fs';
import path from 'path';

const OUT_PATH = path.resolve('docs/js/knowledge_base.js');

// 1. All 195 Sovereign Countries & Capitals
const COUNTRIES_DATA = [
  ["Afghanistan", "Kabul", "Afghani (AFN)", "Pashto, Dari", "Asia"],
  ["Albania", "Tirana", "Lek (ALL)", "Albanian", "Europe"],
  ["Algeria", "Algiers", "Algerian Dinar (DZD)", "Arabic, Berber", "Africa"],
  ["Andorra", "Andorra la Vella", "Euro (EUR)", "Catalan", "Europe"],
  ["Angola", "Luanda", "Kwanza (AOA)", "Portuguese", "Africa"],
  ["Antigua and Barbuda", "Saint John's", "East Caribbean Dollar (XCD)", "English", "North America"],
  ["Argentina", "Buenos Aires", "Argentine Peso (ARS)", "Spanish", "South America"],
  ["Armenia", "Yerevan", "Armenian Dram (AMD)", "Armenian", "Asia"],
  ["Australia", "Canberra", "Australian Dollar (AUD)", "English", "Oceania"],
  ["Austria", "Vienna", "Euro (EUR)", "German", "Europe"],
  ["Azerbaijan", "Baku", "Azerbaijani Manat (AZN)", "Azerbaijani", "Asia"],
  ["Bahamas", "Nassau", "Bahamian Dollar (BSD)", "English", "North America"],
  ["Bahrain", "Manama", "Bahraini Dinar (BHD)", "Arabic", "Asia"],
  ["Bangladesh", "Dhaka", "Bangladeshi Taka (BDT)", "Bengali", "Asia"],
  ["Barbados", "Bridgetown", "Barbadian Dollar (BBD)", "English", "North America"],
  ["Belarus", "Minsk", "Belarusian Ruble (BYN)", "Belarusian, Russian", "Europe"],
  ["Belgium", "Brussels", "Euro (EUR)", "Dutch, French, German", "Europe"],
  ["Belize", "Belmopan", "Belize Dollar (BZD)", "English", "North America"],
  ["Benin", "Porto-Novo", "West African CFA Franc (XOF)", "French", "Africa"],
  ["Bhutan", "Thimphu", "Ngultrum (BTN)", "Dzongkha", "Asia"],
  ["Bolivia", "Sucre (constitutional), La Paz (seat of gov)", "Boliviano (BOB)", "Spanish, Quechua, Aymara", "South America"],
  ["Bosnia and Herzegovina", "Sarajevo", "Convertible Mark (BAM)", "Bosnian, Croatian, Serbian", "Europe"],
  ["Botswana", "Gaborone", "Pula (BWP)", "English, Setswana", "Africa"],
  ["Brazil", "Brasília", "Brazilian Real (BRL)", "Portuguese", "South America"],
  ["Brunei", "Bandar Seri Begawan", "Brunei Dollar (BND)", "Malay", "Asia"],
  ["Bulgaria", "Sofia", "Bulgarian Lev (BGN)", "Bulgarian", "Europe"],
  ["Burkina Faso", "Ouagadougou", "West African CFA Franc (XOF)", "French", "Africa"],
  ["Burundi", "Gitega", "Burundian Franc (BIF)", "Kirundi, French, English", "Africa"],
  ["Cabo Verde", "Praia", "Cape Verdean Escudo (CVE)", "Portuguese", "Africa"],
  ["Cambodia", "Phnom Penh", "Riel (KHR)", "Khmer", "Asia"],
  ["Cameroon", "Yaoundé", "Central African CFA Franc (XAF)", "French, English", "Africa"],
  ["Canada", "Ottawa", "Canadian Dollar (CAD)", "English, French", "North America"],
  ["Central African Republic", "Bangui", "Central African CFA Franc (XAF)", "Sango, French", "Africa"],
  ["Chad", "N'Djamena", "Central African CFA Franc (XAF)", "French, Arabic", "Africa"],
  ["Chile", "Santiago", "Chilean Peso (CLP)", "Spanish", "South America"],
  ["China", "Beijing", "Renminbi / Yuan (CNY)", "Standard Chinese (Mandarin)", "Asia"],
  ["Colombia", "Bogotá", "Colombian Peso (COP)", "Spanish", "South America"],
  ["Comoros", "Moroni", "Comorian Franc (KMF)", "Comorian, French, Arabic", "Africa"],
  ["Congo (Democratic Republic of)", "Kinshasa", "Congolese Franc (CDF)", "French", "Africa"],
  ["Congo (Republic of)", "Brazzaville", "Central African CFA Franc (XAF)", "French", "Africa"],
  ["Costa Rica", "San José", "Costa Rican Colón (CRC)", "Spanish", "North America"],
  ["Croatia", "Zagreb", "Euro (EUR)", "Croatian", "Europe"],
  ["Cuba", "Havana", "Cuban Peso (CUP)", "Spanish", "North America"],
  ["Cyprus", "Nicosia", "Euro (EUR)", "Greek, Turkish", "Europe"],
  ["Czech Republic (Czechia)", "Prague", "Czech Koruna (CZK)", "Czech", "Europe"],
  ["Denmark", "Copenhagen", "Danish Krone (DKK)", "Danish", "Europe"],
  ["Djibouti", "Djibouti", "Djiboutian Franc (DJF)", "Arabic, French", "Africa"],
  ["Dominica", "Roseau", "East Caribbean Dollar (XCD)", "English", "North America"],
  ["Dominican Republic", "Santo Domingo", "Dominican Peso (DOP)", "Spanish", "North America"],
  ["Ecuador", "Quito", "United States Dollar (USD)", "Spanish", "South America"],
  ["Egypt", "Cairo", "Egyptian Pound (EGP)", "Arabic", "Africa"],
  ["El Salvador", "San Salvador", "United States Dollar (USD)", "Spanish", "North America"],
  ["Equatorial Guinea", "Malabo", "Central African CFA Franc (XAF)", "Spanish, French, Portuguese", "Africa"],
  ["Eritrea", "Asmara", "Nakfa (ERN)", "Tigrinya, Arabic, English", "Africa"],
  ["Estonia", "Tallinn", "Euro (EUR)", "Estonian", "Europe"],
  ["Eswatini", "Mbabane (administrative), Lobamba (royal)", "Lilangeni (SZL)", "Swazi, English", "Africa"],
  ["Ethiopia", "Addis Ababa", "Ethiopian Birr (ETB)", "Amharic", "Africa"],
  ["Fiji", "Suva", "Fijian Dollar (FJD)", "English, Fijian, Fiji Hindi", "Oceania"],
  ["Finland", "Helsinki", "Euro (EUR)", "Finnish, Swedish", "Europe"],
  ["France", "Paris", "Euro (EUR)", "French", "Europe"],
  ["Gabon", "Libreville", "Central African CFA Franc (XAF)", "French", "Africa"],
  ["Gambia", "Banjul", "Dalasi (GMD)", "English", "Africa"],
  ["Georgia", "Tbilisi", "Georgian Lari (GEL)", "Georgian", "Asia"],
  ["Germany", "Berlin", "Euro (EUR)", "German", "Europe"],
  ["Ghana", "Accra", "Ghanaian Cedi (GHS)", "English", "Africa"],
  ["Greece", "Athens", "Euro (EUR)", "Greek", "Europe"],
  ["Grenada", "Saint George's", "East Caribbean Dollar (XCD)", "English", "North America"],
  ["Guatemala", "Guatemala City", "Guatemalan Quetzal (GTQ)", "Spanish", "North America"],
  ["Guinea", "Conakry", "Guinean Franc (GNF)", "French", "Africa"],
  ["Guinea-Bissau", "Bissau", "West African CFA Franc (XOF)", "Portuguese", "Africa"],
  ["Guyana", "Georgetown", "Guyanese Dollar (GYD)", "English", "South America"],
  ["Haiti", "Port-au-Prince", "Haitian Gourde (HTG)", "Haitian Creole, French", "North America"],
  ["Honduras", "Tegucigalpa", "Honduran Lempira (HNL)", "Spanish", "North America"],
  ["Hungary", "Budapest", "Hungarian Forint (HUF)", "Hungarian", "Europe"],
  ["Iceland", "Reykjavik", "Icelandic Króna (ISK)", "Icelandic", "Europe"],
  ["India", "New Delhi", "Indian Rupee (INR / ₹)", "Hindi, English (22 scheduled languages)", "Asia"],
  ["Indonesia", "Jakarta (transitioning to Nusantara)", "Indonesian Rupiah (IDR)", "Indonesian", "Asia"],
  ["Iran", "Tehran", "Iranian Rial (IRR)", "Persian", "Asia"],
  ["Iraq", "Baghdad", "Iraqi Dinar (IQD)", "Arabic, Kurdish", "Asia"],
  ["Ireland", "Dublin", "Euro (EUR)", "Irish, English", "Europe"],
  ["Israel", "Jerusalem", "Israeli New Shekel (ILS)", "Hebrew", "Asia"],
  ["Italy", "Rome", "Euro (EUR)", "Italian", "Europe"],
  ["Ivory Coast (Côte d'Ivoire)", "Yamoussoukro", "West African CFA Franc (XOF)", "French", "Africa"],
  ["Jamaica", "Kingston", "Jamaican Dollar (JMD)", "English", "North America"],
  ["Japan", "Tokyo", "Japanese Yen (JPY / ¥)", "Japanese", "Asia"],
  ["Jordan", "Amman", "Jordanian Dinar (JOD)", "Arabic", "Asia"],
  ["Kazakhstan", "Astana", "Kazakhstani Tenge (KZT)", "Kazakh, Russian", "Asia"],
  ["Kenya", "Nairobi", "Kenyan Shilling (KES)", "Swahili, English", "Africa"],
  ["Kiribati", "South Tarawa", "Australian Dollar / Kiribati Dollar", "English, Gilbertese", "Oceania"],
  ["Kuwait", "Kuwait City", "Kuwaiti Dinar (KWD)", "Arabic", "Asia"],
  ["Kyrgyzstan", "Bishkek", "Kyrgyzstani Som (KGS)", "Kyrgyz, Russian", "Asia"],
  ["Laos", "Vientiane", "Lao Kip (LAK)", "Lao", "Asia"],
  ["Latvia", "Riga", "Euro (EUR)", "Latvian", "Europe"],
  ["Lebanon", "Beirut", "Lebanese Pound (LBP)", "Arabic", "Asia"],
  ["Lesotho", "Maseru", "Lesotho Loti (LSL)", "Sesotho, English", "Africa"],
  ["Liberia", "Monrovia", "Liberian Dollar (LRD)", "English", "Africa"],
  ["Libya", "Tripoli", "Libyan Dinar (LYD)", "Arabic", "Africa"],
  ["Liechtenstein", "Vaduz", "Swiss Franc (CHF)", "German", "Europe"],
  ["Lithuania", "Vilnius", "Euro (EUR)", "Lithuanian", "Europe"],
  ["Luxembourg", "Luxembourg City", "Euro (EUR)", "Luxembourgish, French, German", "Europe"],
  ["Madagascar", "Antananarivo", "Malagasy Ariary (MGA)", "Malagasy, French", "Africa"],
  ["Malawi", "Lilongwe", "Malawian Kwacha (MWK)", "English, Chichewa", "Africa"],
  ["Malaysia", "Kuala Lumpur (federal), Putrajaya (administrative)", "Malaysian Ringgit (MYR)", "Malay", "Asia"],
  ["Maldives", "Malé", "Maldivian Rufiyaa (MVR)", "Dhivehi", "Asia"],
  ["Mali", "Bamako", "West African CFA Franc (XOF)", "Bambara (official national language)", "Africa"],
  ["Malta", "Valletta", "Euro (EUR)", "Maltese, English", "Europe"],
  ["Marshall Islands", "Majuro", "United States Dollar (USD)", "Marshallese, English", "Oceania"],
  ["Mauritania", "Nouakchott", "Mauritanian Ouguiya (MRU)", "Arabic", "Africa"],
  ["Mauritius", "Port Louis", "Mauritian Rupee (MUR)", "English, French", "Africa"],
  ["Mexico", "Mexico City", "Mexican Peso (MXN)", "Spanish", "North America"],
  ["Micronesia", "Palikir", "United States Dollar (USD)", "English", "Oceania"],
  ["Moldova", "Chișinău", "Moldovan Leu (MDL)", "Romanian", "Europe"],
  ["Monaco", "Monaco", "Euro (EUR)", "French", "Europe"],
  ["Mongolia", "Ulaanbaatar", "Mongolian Tögrög (MNT)", "Mongolian", "Asia"],
  ["Montenegro", "Podgorica", "Euro (EUR)", "Montenegrin", "Europe"],
  ["Morocco", "Rabat", "Moroccan Dirham (MAD)", "Arabic, Berber", "Africa"],
  ["Mozambique", "Maputo", "Mozambican Metical (MZN)", "Portuguese", "Africa"],
  ["Myanmar (Burma)", "Naypyidaw", "Kyat (MMK)", "Burmese", "Asia"],
  ["Namibia", "Windhoek", "Namibian Dollar (NAD)", "English", "Africa"],
  ["Nauru", "Yaren (de facto district)", "Australian Dollar (AUD)", "Nauruan, English", "Oceania"],
  ["Nepal", "Kathmandu", "Nepalese Rupee (NPR)", "Nepali", "Asia"],
  ["Netherlands", "Amsterdam (constitutional), The Hague (seat of government)", "Euro (EUR)", "Dutch", "Europe"],
  ["New Zealand", "Wellington", "New Zealand Dollar (NZD)", "English, Māori, NZ Sign Language", "Oceania"],
  ["Nicaragua", "Managua", "Nicaraguan Córdoba (NIO)", "Spanish", "North America"],
  ["Niger", "Niamey", "West African CFA Franc (XOF)", "French", "Africa"],
  ["Nigeria", "Abuja", "Nigerian Naira (NGN)", "English", "Africa"],
  ["North Korea", "Pyongyang", "North Korean Won (KPW)", "Korean", "Asia"],
  ["North Macedonia", "Skopje", "Macedonian Denar (MKD)", "Macedonian, Albanian", "Europe"],
  ["Norway", "Oslo", "Norwegian Krone (NOK)", "Norwegian", "Europe"],
  ["Oman", "Muscat", "Omani Rial (OMR)", "Arabic", "Asia"],
  ["Pakistan", "Islamabad", "Pakistani Rupee (PKR)", "Urdu, English", "Asia"],
  ["Palau", "Ngerulmud", "United States Dollar (USD)", "Palauan, English", "Oceania"],
  ["Panama", "Panama City", "Panamanian Balboa (PAB), US Dollar", "Spanish", "North America"],
  ["Papua New Guinea", "Port Moresby", "Papua New Guinean Kina (PGK)", "English, Tok Pisin, Hiri Motu", "Oceania"],
  ["Paraguay", "Asunción", "Paraguayan Guaraní (PYG)", "Spanish, Guaraní", "South America"],
  ["Peru", "Lima", "Peruvian Sol (PEN)", "Spanish, Quechua, Aymara", "South America"],
  ["Philippines", "Manila", "Philippine Peso (PHP)", "Filipino, English", "Asia"],
  ["Poland", "Warsaw", "Polish Złoty (PLN)", "Polish", "Europe"],
  ["Portugal", "Lisbon", "Euro (EUR)", "Portuguese", "Europe"],
  ["Qatar", "Doha", "Qatari Riyal (QAR)", "Arabic", "Asia"],
  ["Romania", "Bucharest", "Romanian Leu (RON)", "Romanian", "Europe"],
  ["Russia", "Moscow", "Russian Ruble (RUB)", "Russian", "Europe / Asia"],
  ["Rwanda", "Kigali", "Rwandan Franc (RWF)", "Kinyarwanda, French, English, Swahili", "Africa"],
  ["Saint Kitts and Nevis", "Basseterre", "East Caribbean Dollar (XCD)", "English", "North America"],
  ["Saint Lucia", "Castries", "East Caribbean Dollar (XCD)", "English", "North America"],
  ["Saint Vincent and the Grenadines", "Kingstown", "East Caribbean Dollar (XCD)", "English", "North America"],
  ["Samoa", "Apia", "Samoan Tālā (WST)", "Samoan, English", "Oceania"],
  ["San Marino", "San Marino", "Euro (EUR)", "Italian", "Europe"],
  ["Sao Tome and Principe", "São Tomé", "São Tomé and Príncipe Dobra (STN)", "Portuguese", "Africa"],
  ["Saudi Arabia", "Riyadh", "Saudi Riyal (SAR)", "Arabic", "Asia"],
  ["Senegal", "Dakar", "West African CFA Franc (XOF)", "French", "Africa"],
  ["Serbia", "Belgrade", "Serbian Dinar (RSD)", "Serbian", "Europe"],
  ["Seychelles", "Victoria", "Seychellois Rupee (SCR)", "Seychellois Creole, English, French", "Africa"],
  ["Sierra Leone", "Freetown", "Sierra Leonean Leone (SLE)", "English", "Africa"],
  ["Singapore", "Singapore", "Singapore Dollar (SGD)", "English, Malay, Mandarin, Tamil", "Asia"],
  ["Slovakia", "Bratislava", "Euro (EUR)", "Slovak", "Europe"],
  ["Slovenia", "Ljubljana", "Euro (EUR)", "Slovene", "Europe"],
  ["Solomon Islands", "Honiara", "Solomon Islands Dollar (SBD)", "English", "Oceania"],
  ["Somalia", "Mogadishu", "Somali Shilling (SOS)", "Somali, Arabic", "Africa"],
  ["South Africa", "Pretoria (executive), Cape Town (legislative), Bloemfontein (judicial)", "South African Rand (ZAR)", "12 official languages including Zulu, Xhosa, Afrikaans, English", "Africa"],
  ["South Korea", "Seoul", "South Korean Won (KRW)", "Korean", "Asia"],
  ["South Sudan", "Juba", "South Sudanese Pound (SSP)", "English", "Africa"],
  ["Spain", "Madrid", "Euro (EUR)", "Spanish", "Europe"],
  ["Sri Lanka", "Sri Jayawardenepura Kotte (legislative), Colombo (executive/commercial)", "Sri Lankan Rupee (LKR)", "Sinhala, Tamil", "Asia"],
  ["Sudan", "Khartoum", "Sudanese Pound (SDG)", "Arabic, English", "Africa"],
  ["Suriname", "Paramaribo", "Surinamese Dollar (SRD)", "Dutch", "South America"],
  ["Sweden", "Stockholm", "Swedish Krona (SEK)", "Swedish", "Europe"],
  ["Switzerland", "Bern (federal city)", "Swiss Franc (CHF)", "German, French, Italian, Romansh", "Europe"],
  ["Syria", "Damascus", "Syrian Pound (SYP)", "Arabic", "Asia"],
  ["Tajikistan", "Dushanbe", "Tajikistani Somoni (TJS)", "Tajik", "Asia"],
  ["Tanzania", "Dodoma (official), Dar es Salaam (commercial)", "Tanzanian Shilling (TZS)", "Swahili, English", "Africa"],
  ["Thailand", "Bangkok", "Thai Baht (THB)", "Thai", "Asia"],
  ["Timor-Leste", "Dili", "United States Dollar (USD)", "Tetum, Portuguese", "Asia"],
  ["Togo", "Lomé", "West African CFA Franc (XOF)", "French", "Africa"],
  ["Tonga", "Nukuʻalofa", "Tongan Paʻanga (TOP)", "Tongan, English", "Oceania"],
  ["Trinidad and Tobago", "Port of Spain", "Trinidad and Tobago Dollar (TTD)", "English", "North America"],
  ["Tunisia", "Tunis", "Tunisian Dinar (TND)", "Arabic", "Africa"],
  ["Turkey", "Ankara", "Turkish Lira (TRY)", "Turkish", "Europe / Asia"],
  ["Turkmenistan", "Ashgabat", "Turkmenistani Manat (TMT)", "Turkmen", "Asia"],
  ["Tuvalu", "Funafuti", "Tuvaluan Dollar / Australian Dollar", "Tuvaluan, English", "Oceania"],
  ["Uganda", "Kampala", "Ugandan Shilling (UGX)", "Swahili, English", "Africa"],
  ["Ukraine", "Kyiv", "Ukrainian Hryvnia (UAH)", "Ukrainian", "Europe"],
  ["United Arab Emirates (UAE)", "Abu Dhabi", "UAE Dirham (AED)", "Arabic", "Asia"],
  ["United Kingdom (UK)", "London", "British Pound Sterling (GBP / £)", "English", "Europe"],
  ["United States (USA)", "Washington, D.C.", "United States Dollar (USD / $)", "English (de facto)", "North America"],
  ["Uruguay", "Montevideo", "Uruguayan Peso (UYU)", "Spanish", "South America"],
  ["Uzbekistan", "Tashkent", "Uzbekistani Som (UZS)", "Uzbek", "Asia"],
  ["Vanuatu", "Port Vila", "Vanuatu Vatu (VUV)", "Bislama, English, French", "Oceania"],
  ["Vatican City", "Vatican City", "Euro (EUR)", "Italian, Latin", "Europe"],
  ["Venezuela", "Caracas", "Venezuelan Bolívar (VES)", "Spanish", "South America"],
  ["Vietnam", "Hanoi", "Vietnamese Đồng (VND)", "Vietnamese", "Asia"],
  ["Yemen", "Sana'a (constitutional), Aden (interim)", "Yemeni Rial (YER)", "Arabic", "Asia"],
  ["Zambia", "Lusaka", "Zambian Kwacha (ZMW)", "English", "Africa"],
  ["Zimbabwe", "Harare", "Zimbabwe Gold (ZiG) / US Dollar", "16 official languages including Shona, Ndebele, English", "Africa"]
];

console.log(`Loaded ${COUNTRIES_DATA.length} sovereign countries and capitals.`);
